# Generated by Django 4.2.2 on 2023-06-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_api', '0002_alter_mentor_bio_alter_mentor_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='birthD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='track',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birthD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='track',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
