# Generated by Django 4.2.2 on 2023-06-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_api', '0003_mentor_birthd_mentor_city_mentor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='intersts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='intersts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='track',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
