# Generated by Django 4.2.2 on 2023-06-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_api', '0004_mentor_intersts_student_intersts_alter_mentor_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='birthD',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='intersts',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='track',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthD',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='intersts',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='track',
        ),
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intersts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
