# Generated by Django 4.2.2 on 2023-06-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_api', '0006_bookingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('zoom_link', models.CharField(max_length=255)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='track',
            field=models.CharField(default='web', max_length=100),
        ),
        migrations.DeleteModel(
            name='BookingSession',
        ),
        migrations.AddField(
            model_name='session',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to='mentor_api.mentor'),
        ),
        migrations.AddField(
            model_name='session',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentor_api.request'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='mentor_api.student'),
        ),
        migrations.AddField(
            model_name='request',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_api.mentor'),
        ),
        migrations.AddField(
            model_name='request',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_api.student'),
        ),
    ]
