# Generated by Django 4.2.2 on 2023-06-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_api', '0007_request_session_mentor_track_delete_bookingsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='track',
        ),
    ]
