# Generated by Django 4.2.2 on 2023-07-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_api', '0008_remove_mentor_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests', to='mentor_api.mentor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='mentor_api.student'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='zoom_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
