# Generated by Django 4.2.2 on 2023-07-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_api', '0009_alter_request_mentor_alter_request_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_api.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_api.student')),
            ],
        ),
    ]
